version: "2.0"
services:
  recepies:
    image: recepies
    ports:
      - "3000:3000"
    environment:
      - MONGODB_HOST=172.17.0.1
      - DATABASE=recepies
      - FILEBASE=/files
      - SECRET=eEMAr0UrJmyrLvwA2jcd8tPC93NTmE5cWpx9abAkc5quNysKZLwlxPHvOgNO
      - PROTECTED_ENDPOINTS="recipe:create,recipe:update,recipe:delete,recipe:upload"
    volumes:
      - /tmp/files:/files
